# Runs unit tests and pre-commit on all pushed commits.

name: CI
on:
  push:
  workflow_dispatch:

jobs:

  run-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Install Task
        uses: Arduino/actions/setup-taskfile@master
        with:
          version: 3.x
      - name: Update python distutils
        run: sudo apt update && sudo apt-get install python3.8-distutils -y
      - uses: actions/checkout@v2
      - name: Run pre-commit analysis
        run: task pre-commit

  run-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: Install Task
        uses: Arduino/actions/setup-taskfile@master
        with:
          version: 3.x
      - name: Update python distutils
        run: sudo apt update && sudo apt-get install python3.8-distutils -y
      - uses: actions/checkout@v2
      - name: Run unit tests
        run: task unit
